#!/usr/bin/env python3
"""The repository's rights map: exactly one license and one rights holder for every published file.

Content files declare their own license in front matter; everything else follows its folder.
`validate_release.py --write-manifest` writes the REUSE.toml this map implies, and the
validator fails when REUSE.toml, LICENSES/, or a declared license drifts from the map.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REFERENCE_USE = "LicenseRef-Lizheng-Reference-Use-1.0"
RETAINED = "LicenseRef-Original-Rights-Retained"
LICENSE_TEXTS = {
    "MIT": "LICENSES/MIT.txt",
    "CC0-1.0": "LICENSES/CC0-1.0.txt",
    "CC-BY-4.0": "LICENSES/CC-BY-4.0.txt",
    REFERENCE_USE: f"LICENSES/{REFERENCE_USE}.md",
    RETAINED: f"LICENSES/{RETAINED}.md",
}
CONTENT_LICENSES = ("CC-BY-4.0", REFERENCE_USE, RETAINED)
CONTENT_DIRS = ("corpus/", "context/", "examples/")
METADATA_DIRS = ("catalog/", "config/", "index/")
METADATA_FILES = {"INDEX.md", "release-manifest.json"}
# These state the rights of other files rather than carrying content of their own.
RIGHTS_DOCUMENTS = {"LICENSE.md", "LICENSE-CONTENT.md", "REUSE.toml"}
REUSE_TOML = "REUSE.toml"

MAINTAINER = "2026 Yuzheng Sun"
YUZHENG = "Yuzheng Sun (立正)"
SPEAKERS = "Yuzheng Sun (立正); guests and other speakers keep the rights in their own words"
AUTHORS = "The original authors named in each file"


def declared(path: Path) -> dict:
    """The rights fields a content file declares about itself."""
    if path.suffix == ".json":
        data = json.loads(path.read_text(encoding="utf-8"))
        return {"license": data.get("license")}
    match = re.match(r"\A---\n(.*?)\n---\n", path.read_text(encoding="utf-8"), re.S)
    fields = {}
    for line in match[1].splitlines() if match else []:
        key, _, value = line.partition(":")
        if key.strip() in {"license", "rights_scope"}:
            try:
                fields[key.strip()] = json.loads(value.strip())
            except json.JSONDecodeError:
                fields[key.strip()] = value.strip()
    return fields


def file_rights(relative: str, root: Path = ROOT) -> tuple[str, str] | None:
    """(license, rights holder) for one repository path; None for the rights documents themselves."""
    if relative in RIGHTS_DOCUMENTS or relative.startswith("LICENSES/"):
        return None
    if relative.startswith(METADATA_DIRS) or relative in METADATA_FILES:
        return "CC0-1.0", MAINTAINER
    if relative.startswith(CONTENT_DIRS):
        fields = declared(root / relative)
        license = str(fields.get("license") or "")
        if license == RETAINED:
            return license, AUTHORS
        if fields.get("rights_scope") == "publisher-authorized-transcript":
            return license, SPEAKERS
        return license, YUZHENG
    return "MIT", MAINTAINER


def rights_map(files: list[str], root: Path = ROOT) -> dict[str, tuple[str, str]]:
    rights = {}
    for relative in sorted(files):
        value = file_rights(relative, root)
        if value:
            rights[relative] = value
    return rights


def annotation_groups(rights: dict[str, tuple[str, str]]) -> dict[tuple[str, str], list[str]]:
    """Cover each folder whose files share one license with a single glob; list the rest by name."""
    folders: dict[str, set] = {}
    for path, key in rights.items():
        parts = path.split("/")
        for depth in range(1, len(parts)):
            folders.setdefault("/".join(parts[:depth]), set()).add(key)
    uniform = {folder for folder, keys in folders.items() if len(keys) == 1}
    widest = sorted(folder for folder in uniform if "/".join(folder.split("/")[:-1]) not in uniform)
    groups: dict[tuple[str, str], list[str]] = {}
    for folder in widest:
        groups.setdefault(next(iter(folders[folder])), []).append(f"{folder}/**")
    for path, key in rights.items():
        if not any(path.startswith(folder + "/") for folder in widest):
            groups.setdefault(key, []).append(path)
    return groups


def reuse_toml(rights: dict[str, tuple[str, str]]) -> str:
    order = list(LICENSE_TEXTS)
    groups = sorted(
        annotation_groups(rights).items(),
        key=lambda item: (order.index(item[0][0]) if item[0][0] in order else len(order), item[0][1]),
    )
    lines = [
        "# Generated by scripts/rights.py from each file's declared license; do not edit by hand.",
        "# Plain-language overview: LICENSE.md. Full license texts: LICENSES/.",
        "version = 1",
    ]
    for (license, holder), paths in groups:
        lines += ["", "[[annotations]]", "path = ["]
        lines += [f"  {json.dumps(path, ensure_ascii=False)}," for path in sorted(paths)]
        lines += [
            "]",
            'precedence = "override"',
            f"SPDX-FileCopyrightText = {json.dumps(holder, ensure_ascii=False)}",
            f"SPDX-License-Identifier = {json.dumps(license, ensure_ascii=False)}",
        ]
    return "\n".join(lines) + "\n"


def write(files: list[str], root: Path = ROOT) -> dict[str, tuple[str, str]]:
    rights = rights_map(files, root)
    (root / REUSE_TOML).write_text(reuse_toml(rights), encoding="utf-8")
    return rights


def validate(files: list[str], errors: list[str], root: Path = ROOT) -> dict[str, tuple[str, str]]:
    rights = rights_map(files, root)
    used = set()
    for relative, (license, _) in rights.items():
        if relative.startswith(CONTENT_DIRS) and license not in CONTENT_LICENSES:
            errors.append(f"{relative}: content must declare one of {', '.join(CONTENT_LICENSES)}, not {license!r}")
        elif license not in LICENSE_TEXTS:
            errors.append(f"{relative}: unknown license {license!r}")
        used.add(license)
    expected_texts = {LICENSE_TEXTS[license] for license in used if license in LICENSE_TEXTS}
    present = {str(path.relative_to(root)) for path in (root / "LICENSES").glob("*") if path.is_file()}
    for missing in sorted(expected_texts - present):
        errors.append(f"{missing}: license text is missing")
    for unused in sorted(present - expected_texts):
        errors.append(f"{unused}: license text is not used by any file")
    current = (root / REUSE_TOML).read_text(encoding="utf-8") if (root / REUSE_TOML).is_file() else ""
    if current != reuse_toml(rights):
        errors.append("REUSE.toml is stale; rerun python3 scripts/validate_release.py --write-manifest")
    return rights
